### ISSUE TITLE
网络---无线无法显示

### ISSUE THREAD

**Issue by Ge0Lin** [zhaojh329/xluci2#2]
斐讯K2（H/W A5）
LEDE 17.01
固件在编译前，修改源码设置了WiFi密码。如果按照LEDE源码默认则可以正常显示
无线配置页面无法显示，如图：

[
![2017-11-22 19-20-26](https://user-images.githubusercontent.com/8558090/33125182-6a48d8b0-cfba-11e7-9569-128d0bb136de.png)

**Comment by cohux** [comment]
我也遇到同样的情况 mt7620

**Comment by cohux** [comment]
ar71xx上测试是正常的。
